### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-utils bundle size difference from 1.1.1 to 1951e99d9350a70c2230f3d556f84d33a8d73564
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-utils bundle size difference from 1.1.1 to 2a3db53a3a9545746edb214dd9745cdb45c895e4
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-utils bundle size difference from 1.1.1 to adfa5393c646dd3d10e5ca0de093ea969fff1982
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-utils bundle size difference from 1.1.1 to 25f414144e907ba2cd015f1caf58bb5deb62f6ba
No significant bundle size differences found.

**Pull request merged**
